### ISSUE TITLE
pyextract requirements 

### ISSUE THREAD

**Issue by dsluse** [sibirrer/AstroObjectAnalyser#3]
image_data.py calls pyextract but pyextract is not in the requirements.txt, and I did not find out where this module is available.

**Comment by sibirrer** [comment]
It's here:
https://github.com/sibirrer/pyextractor

I will add it to the requirement

**Comment by dsluse** [comment]
Thanks. I did not realise that pyextractor was pyextract.

**Comment by sibirrer** [comment]
yeah, naming of the package and folder is not consistent. I close this issue for the moment. If you have problems, please re-opne.
